/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_package_keyword = 2,
  sym_config_keyword = 3,
  sym_option_keyword = 4,
  sym_list_keyword = 5,
  sym_identifier = 6,
  sym_unquoted_value = 7,
  sym_double_quoted_string = 8,
  sym_single_quoted_string = 9,
  sym_source_file = 10,
  sym_package_statement = 11,
  sym_config_section = 12,
  sym_option_statement = 13,
  sym_list_statement = 14,
  sym_identifier_or_string = 15,
  sym_value = 16,
  sym_string = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_config_section_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_package_keyword] = "package_keyword",
  [sym_config_keyword] = "config_keyword",
  [sym_option_keyword] = "option_keyword",
  [sym_list_keyword] = "list_keyword",
  [sym_identifier] = "identifier",
  [sym_unquoted_value] = "unquoted_value",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_source_file] = "source_file",
  [sym_package_statement] = "package_statement",
  [sym_config_section] = "config_section",
  [sym_option_statement] = "option_statement",
  [sym_list_statement] = "list_statement",
  [sym_identifier_or_string] = "identifier_or_string",
  [sym_value] = "value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_config_section_repeat1] = "config_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_package_keyword] = sym_package_keyword,
  [sym_config_keyword] = sym_config_keyword,
  [sym_option_keyword] = sym_option_keyword,
  [sym_list_keyword] = sym_list_keyword,
  [sym_identifier] = sym_identifier,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_source_file] = sym_source_file,
  [sym_package_statement] = sym_package_statement,
  [sym_config_section] = sym_config_section,
  [sym_option_statement] = sym_option_statement,
  [sym_list_statement] = sym_list_statement,
  [sym_identifier_or_string] = sym_identifier_or_string,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_config_section_repeat1] = aux_sym_config_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_package_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_config_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_option_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_list_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_package_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_config_section] = {
    .visible = true,
    .named = true,
  },
  [sym_option_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_list_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_or_string] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_config_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 5,
  [13] = 13,
  [14] = 8,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 5,
  [24] = 8,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'l') ADVANCE(44);
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead == 'p') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(25);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'g') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'g') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'k') ADVANCE(6);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 25:
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == 'c') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(20);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_package_keyword);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_package_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_config_keyword);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_config_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_option_keyword);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_option_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_list_keyword);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_list_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_double_quoted_string);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_single_quoted_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 26},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 26},
  [4] = {.lex_state = 26},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 26},
  [7] = {.lex_state = 26},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 26},
  [10] = {.lex_state = 26},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 26},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 26},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 26},
  [19] = {.lex_state = 26},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 26},
  [22] = {.lex_state = 26},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_package_keyword] = ACTIONS(1),
    [sym_config_keyword] = ACTIONS(1),
    [sym_option_keyword] = ACTIONS(1),
    [sym_list_keyword] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_double_quoted_string] = ACTIONS(1),
    [sym_single_quoted_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_package_statement] = STATE(10),
    [sym_config_section] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_package_keyword] = ACTIONS(7),
    [sym_config_keyword] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_option_statement] = STATE(4),
    [sym_list_statement] = STATE(4),
    [sym_identifier_or_string] = STATE(3),
    [sym_string] = STATE(12),
    [aux_sym_config_section_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_package_keyword] = ACTIONS(13),
    [sym_config_keyword] = ACTIONS(13),
    [sym_option_keyword] = ACTIONS(15),
    [sym_list_keyword] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_double_quoted_string] = ACTIONS(21),
    [sym_single_quoted_string] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_option_keyword,
    ACTIONS(27), 1,
      sym_list_keyword,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
    STATE(6), 3,
      sym_option_statement,
      sym_list_statement,
      aux_sym_config_section_repeat1,
  [20] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_option_keyword,
    ACTIONS(27), 1,
      sym_list_keyword,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
    STATE(7), 3,
      sym_option_statement,
      sym_list_statement,
      aux_sym_config_section_repeat1,
  [40] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      sym_double_quoted_string,
      sym_single_quoted_string,
    ACTIONS(31), 5,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
      sym_identifier,
  [56] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_option_keyword,
    ACTIONS(27), 1,
      sym_list_keyword,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
    STATE(7), 3,
      sym_option_statement,
      sym_list_statement,
      aux_sym_config_section_repeat1,
  [76] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_option_keyword,
    ACTIONS(40), 1,
      sym_list_keyword,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
    STATE(7), 3,
      sym_option_statement,
      sym_list_statement,
      aux_sym_config_section_repeat1,
  [96] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 3,
      ts_builtin_sym_end,
      sym_double_quoted_string,
      sym_single_quoted_string,
    ACTIONS(45), 5,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
      sym_identifier,
  [112] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_package_keyword,
    ACTIONS(52), 1,
      sym_config_keyword,
    STATE(9), 3,
      sym_package_statement,
      sym_config_section,
      aux_sym_source_file_repeat1,
  [130] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_package_keyword,
    ACTIONS(9), 1,
      sym_config_keyword,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(9), 3,
      sym_package_statement,
      sym_config_section,
      aux_sym_source_file_repeat1,
  [148] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(2), 1,
      sym_identifier_or_string,
    STATE(5), 1,
      sym_string,
    ACTIONS(59), 2,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 5,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
  [176] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(20), 1,
      sym_identifier_or_string,
    STATE(23), 1,
      sym_string,
    ACTIONS(63), 2,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
  [204] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(12), 1,
      sym_string,
    STATE(22), 1,
      sym_identifier_or_string,
    ACTIONS(21), 2,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [221] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(17), 1,
      sym_identifier_or_string,
    STATE(23), 1,
      sym_string,
    ACTIONS(63), 2,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [238] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_unquoted_value,
    STATE(18), 1,
      sym_string,
    STATE(21), 1,
      sym_value,
    ACTIONS(21), 2,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [255] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
  [266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
  [277] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_unquoted_value,
    STATE(18), 1,
      sym_string,
    STATE(19), 1,
      sym_value,
    ACTIONS(21), 2,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
      sym_option_keyword,
      sym_list_keyword,
  [305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      sym_package_keyword,
      sym_config_keyword,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 3,
      sym_unquoted_value,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 3,
      sym_unquoted_value,
      sym_double_quoted_string,
      sym_single_quoted_string,
  [332] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 20,
  [SMALL_STATE(5)] = 40,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 76,
  [SMALL_STATE(8)] = 96,
  [SMALL_STATE(9)] = 112,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 165,
  [SMALL_STATE(13)] = 176,
  [SMALL_STATE(14)] = 193,
  [SMALL_STATE(15)] = 204,
  [SMALL_STATE(16)] = 221,
  [SMALL_STATE(17)] = 238,
  [SMALL_STATE(18)] = 255,
  [SMALL_STATE(19)] = 266,
  [SMALL_STATE(20)] = 277,
  [SMALL_STATE(21)] = 294,
  [SMALL_STATE(22)] = 305,
  [SMALL_STATE(23)] = 314,
  [SMALL_STATE(24)] = 323,
  [SMALL_STATE(25)] = 332,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_section, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_section, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_section, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_or_string, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_or_string, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_section, 4, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_section_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_section_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_section_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_statement, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_statement, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_statement, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_uci(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "uci",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
